### ISSUE TITLE
If a template is a template literal with a parameter passed to it and no data is available yet, things fail

### ISSUE THREAD

**Issue by kylebuch8** [RHElements/rhelements#103]
With the new changes to the RHElement base class, we've lost the ability to defer the rendering of the template until we have data.

cp-more-like-this is not in master and most likely will be moved out of the repo to another, but cp-more-like-this should not render until we have data supplied to it. It's okay to go ahead and create the shadow root in the constructor, but we need to have a way to delay the appending of the template to the shadow dom.

Maybe we should create a render method as @KamiQuasi keeps suggesting.

**Comment by mwcz** [comment]
@kylebuch8 queueAction works for this too.
