### ISSUE TITLE
npm run dev should be npm run new

### ISSUE THREAD

**Issue by btopro** [RHElements/rhelements#142]
PR pending, amazing work btw; the LRNWebComponents team is picking through things in this as a possible replacement for our tooling workflows.

**Comment by kylebuch8** [comment]
@btopro Thanks for the compliment.

The purpose of `npm run new` is to scaffold a new RHElement and add it to the `/elements` directory. We want to keep `npm run dev` as a script within each RHElement in the `/elements` directory. Does that make sense?

**Comment by btopro** [comment]
ahh ok, as I've been working on a fork of the generator this makes sense. I think it was confusing the wording in the top level repo (or I just can't read). Going to shoot a video later about what we're messing with.

I see you've cleaned up the difference on the initial doc page so closing out :)
