### ISSUE TITLE
404 on homepage for Getting Started page

### ISSUE THREAD

**Issue by LHinson** [RHElements/rhelements#166]
The "get started page" link on the home page gives you a 404. Should link to https://rhelements.github.io/getting-started/ instead of https://rhelements.github.io/get-started

**Comment by mwcz** [comment]
Thanks @LHinson!  Fix coming up.

**Comment by mwcz** [comment]
https://github.com/RHElements/rhelements-documentation/pull/5

**Comment by kylebuch8** [comment]
This was fixed in https://github.com/RHElements/rhelements-documentation/pull/5.
