### ISSUE TITLE
Purpose of all project

### ISSUE THREAD

**Issue by btopro** [RHElements/rhelements#201]
Quick one, what does the all package whose dependencies auto add new elements do? I realize it has a lost of all of them but is it important in tooling elsewhere somehow? Running into issues juggling it w. Legit version numbers at times prepublishing and wanted to know if I'm missing something as to what it is helping a accomplish

**Comment by btopro** [comment]
ok cool yea that's what I was wondering. We've dropped lerna bootstrap for yarn workspaces in https://github.com/elmsln/wcfactory/tree/master/packages/generator-wcfactory/generators/factory/templates and lerna just serves for the local project linking (tho it doesn't seem that all is helping w/ this it appears to be figuring out which depend on each other and ensuring they are linked).

We've been running into issues w/ all management when it came to publishing (versions being off at times) though are looking for a solution to help w/ storybook getting mad when multiple elements have local dependencies (like element-one has polymer as well as element-two but for packaging purposes they each then have their own copy local copy instead of hoisting). This works great for dev of individual elements as well as build flow but for storybook / webpack it seems to get tripped up claiming there are multiple definitions instead of resolving them to one copy :\

**Comment by mwcz** [comment]
Removed the all project in #207
