### ISSUE TITLE
rh-cta example

### ISSUE THREAD

**Issue by starryeyez024** [RHElements/rhelements#219]
In storybook it shows:
```
<rh-cta>Become a Member</rh-cta>
```
but probably should be:
```
<rh-cta><a href="foo.com">Become a Member</a></rh-cta>
```

is that right?

**Comment by markcaron** [comment]
You're right, this is a mistake.

**Comment by castastrophe** [comment]
It looks like this was already fixed in the repo.  +1 closing this out!
