### ISSUE TITLE
Reveal UMD is not actually UMD

### ISSUE THREAD

**Issue by KamiQuasi** [RHElements/rhelements#224]
$title says it all `reveal.umd.js` is not actually UMD

**Comment by mwcz** [comment]
Good catch.  That file, during the build, winds up embedded in `rhelement.umd.js`.  It isn't/shouldn't ever be used on its own, so the build should be updated to delete it after `rhelement.umd.js` is created.

**Comment by castastrophe** [comment]
This seems like a dupe now of https://github.com/RHElements/rhelements/issues/227 which more specifically calls out the fix.  @KamiQuasi I'm going to close out this one but feel free to reopen if you think 227 doesn't address the issue.
