### ISSUE TITLE
revisit methods of preventing FOUC

### ISSUE THREAD

**Issue by mwcz** [RHElements/rhelements#29]
links:
 - [:defined](https://developers.google.com/web/fundamentals/web-components/customelements#prestyle)
 - [howto-tabs using :defined](https://github.com/GoogleChromeLabs/howto-components/blob/master/elements/howto-tabs/demo.html)

:defined cannot be polyfilled

**Comment by mwcz** [comment]
Idea from @castastrophe: for an `unresolved`-style solution where the whole body is hidden, we could reveal the body when elements in the viewport have upgraded, instead of waiting for all elements to upgrade.

**Comment by mwcz** [comment]
There are bound to be tons of reflows as the elements upgrade.  I wonder if having the entire body `display: none`'d removes the performance penalty of those reflows.  Does the browser skip reflows if everything is hidden?

**Comment by kylebuch8** [comment]
@mwcz - Unresolved is what Polymer does but I'm not sure what implications this has for the scenario where Javascript is disabled. I think we'd need to have a `<noscript>` tag with some styles that would remove `display: none` from the body.

**Comment by mwcz** [comment]
@kylebuch8 definitely, that is planned.  Since it isn't something we can bake into rhelements itself, it will have to be included in the docs, perhaps in a "pro tips" section.  For the Portal, it's easy enough to include the noscript in the chroming.
