### ISSUE TITLE
move customElements.define out of element boilerplate and into Rhelement.create

### ISSUE THREAD

**Issue by mwcz** [RHElements/rhelements#36]
We could move the boilerplate...

```js
window.customElements.define("rh-card", RhCard);
```

Into the Rhelement class's constructor.

**Comment by kylebuch8** [comment]
After some investigation, we found that this won't work. :(

**Comment by mwcz** [comment]
There is the option of wrapping the customElements.define, either in a static method on the Rhelement class or in another module entirely.

rhelement.js:
```js
class Rhelement extends HTMLElement {
  static create(name, rhe) {
    customElements.define(name, rhe);
  }
}
```

rh-card.js:
```js
import Rhelement from "../rhelement/rhelement.js";

Rhelement.create("rh-card", class extends Rhelement {
  constructor() {} 
  // etc
});
```

This way the duplicated boilerplate is moved into one place, it gives us a "hook" to add more functionality at "define time" if we ever need to, and it isn't bound to whether the Rhelement has been constructed or not, which IIRC is the reason we failed last week to come up with a working solution.

**Comment by kylebuch8** [comment]
@KamiQuasi - Any thoughts on this?
