### ISSUE TITLE
add `type` attribute to rhelements

### ISSUE THREAD

**Issue by mwcz** [RHElements/rhelements#52]
When a rhelement is upgraded, it should add an attribute to itself signifying what type of component it is, for example:

- container
- content
- combo

Also, add a question to the generator to pick the type.

@castastrophe @starryeyez024 @kylebuch8 could you all review that this all makes sense?  I came in halfway into the discussion and could easily have missed some things.

Brainstorm impl:

rh-card.js
```js
class RhCard extends Rhelement {
  get type() {
    return Rhelement.Types.Container;
  }
}
```

Rhelement base class adding the attribute:

rhelement.js
```js
class Rhelement extends HTMLElement {
  static get Types() {
    return {
      Container: "container",
      Content: "content",
      Combo: "combo",
    };
  }
  connectedCallback() {
    this.setAttribute("type", this.type);
  }
}
```

**Comment by starryeyez024** [comment]
This looks accurate @mwcz; however I don't know that we ever voted yes to "combo" instead of "pattern". I don't mind the three C's, but I think @KrystalMoore16 had objections?

**Comment by mwcz** [comment]
Just for fun, I'm reconsidering using the `type` attribute.  I could go either way, but it might be good to use something else because there will probably be elements in the future who would really want to use `type` for their own custom attributes, like an `rh-input` for example.

Here are some other options.  These would each be added at runtime and visible in the element inspector.

### Plain attribute

```html
<rh-card container></rh-card>
```

### rh-prefixed attribute
Like the above, but prefixed with `rh-` to avoid name conflicts on the offchance that an element wants to have a `container`, or more likely, a `content` attribute of its own.
```html
<rh-card rh-container></rh-card>
```

### rh-type
Like the original `type` proposal, but the attribute is prefixed with `rh-`, leaving `type` available for any element that wants to use it.
```html
<rh-card rh-type="container"></rh-card>
```

### pattern-type
This one might have the most clarity.  Is "pattern" the right word here?
```html
<rh-card pattern-type="container"></rh-card>
```

After writing this I'm leaning towards not using plain old `type`, but I'm not sure how to choose.  Thoughts?

**Comment by markcaron** [comment]
I like `rh-type`

**Comment by castastrophe** [comment]
Is there a way to abstract the types into a configuration file so that it could be easily updated rather than in the JS directly?

**Comment by KrystalMoore16** [comment]
Right, @starryeyez024. I still prefer "pattern" over "combo." I don't mind using those interchangeably during conversation, but pattern is my preference for clarity and consistency with other design systems. It's true that we can always be different, but I think "pattern" makes more sense.

**Comment by castastrophe** [comment]
Example of the configuration file concept I'm referring to: https://github.com/PatternBuilder/pattern-kit/blob/master/.pk-config.yml Pattern-kit has a pk-config file which contains the defined categories.
