### ISSUE TITLE
discuss renaming built files

### ISSUE THREAD

**Issue by mwcz** [RHElements/rhelements#53]
Proposed change:

1. rename `rh-foo/rh-foo.compiled.js` to `rh-foo/rh-foo.es5.js`
2. rename `rh-foo/rh-foo.js` to `rh-foo/rh-foo.mjs`

Reasoning:

For the first one, "es5" conveys the purpose of the file more clearly than "compiled".  For the second, there are some [good reasons](http://2ality.com/2017/05/es-module-specifiers.html) to use the `mjs` file extension for ES modules.

These changes will make more clear to contributors and users what the purpose of the two built files are.

**Comment by KamiQuasi** [comment]
I think these are really appropriate changes to make. Given the import syntax rules for modules it makes sense, and doesn't add any complexity to the usage.

**Comment by mwcz** [comment]
@kylebuch8, what do you think?

**Comment by kylebuch8** [comment]
@mwcz - I'm good with changing .compiled.js to .es5.js but I'm not so sure .mjs is the way to go. Some Google searches show that other teams have tried this but have then struggled with Webpack and CommonJS.

**Comment by mwcz** [comment]
Good suggestion from Doug: `.umd.js` instead of `.es5.js`.  I think I'm onboard with that.
