### ISSUE TITLE
Change Rhelement class name to RHElement

### ISSUE THREAD

**Issue by kylebuch8** [RHElements/rhelements#71]
@KamiQuasi thinks we should fix the capitalization of our Rhelement class. I agree with him. It will make things more consistent with our brand. If HTMLElement does it, why can't we?

@mwcz @starryeyez024 - Objections?

And yes, I realize that we'll need to update all of the files that depend on Rhelement but I think things are still early enough to make this change.

**Comment by mwcz** [comment]
I like "r".

Just kidding!  This sounds good to me.

**Comment by KamiQuasi** [comment]
As justification, I just like that it looks more like HTMLElement.

**Comment by KamiQuasi** [comment]
https://github.com/RHElements/rhelements/pull/74

**Comment by starryeyez024** [comment]
Works for me.
