### ISSUE TITLE
RHElement Generator should add :host([hidden]) to SCSS

### ISSUE THREAD

**Issue by markcaron** [RHElements/rhelements#82]
`:host([hidden]) { display: none }` is necessary for all components, per [best practices](https://developers.google.com/web/fundamentals/web-components/best-practices).

The RHElements Generator should add this line to the SCSS so contributing devs don't forget to add this bit.

**Comment by kylebuch8** [comment]
Fixed in https://github.com/RHElements/generator-rhelement/commit/300f267e2257c2d69ba5a20c6eb337935d88fd82.
